### ISSUE TITLE
v0.93 does not compile on cygwin

### ISSUE THREAD

**Issue by obouizi** [traviscross/mtr#333] opened 2020-02-12 10:31 UTC
Hi,

I get the following error when compiling the v0.93 on cygwin:
`  CC       packet/wait_cygwin.o`
`packet/wait_cygwin.c: In function ‘wait_for_activity’:`
`packet/wait_cygwin.c:61:13: error: ‘errno’ undeclared (first use in this function); did you mean ‘error’?`

It can be fixed by adding #include <errno.h> in packet/wait_cygwin.c (after #include <error.h>)

**Comment by rewolff** [comment] 2020-02-12 11:20
Can you try the current sources then? Did I do it correctly? (I don't have windows to run cygwin).

**Comment by obouizi** [comment] 2020-02-13 00:00
It is fine now, it compiles correctly but not flawlessly.
I attached a txt file with the compiler messages. It was done with GCC 7.4.0.

[mtr_and_cygwin.txt](https://github.com/traviscross/mtr/files/4195795/mtr_and_cygwin.txt)

**Comment by rewolff** [comment] 2020-02-13 08:20
Hi, Can you check it out again, maybe I fixed it a bit?

**Comment by obouizi** [comment] 2020-02-13 08:34
Perfect ! No more warning :-) Nice job!

**Comment by rewolff** [comment] 2020-02-13 08:39
Glad that I was able to fix it without having access to the system myself. 
The problem is that such changes MIGHT cause problems for others that have another version of the compiler software and things like that. Anyway... lets close this for now.

**Closed by rewolff** 2020-02-13 08:39 UTC
