### ISSUE TITLE
Fails to handle only v6 nameservers defined in resolv.conf

### ISSUE THREAD

**Issue by Zugschlus** [traviscross/mtr#105] opened 2016-02-25 10:50 UTC
Hi,

this is me forwarding a long-standing bug report against mtr-tiny in Debian GNU/Linux, 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773496.

If only IPv6 nameservers are defined in /etc/resolv.conf mtr-tiny dies with an error "No nameservers defined.". It also fails to clean up the screen afterwards leaving a corrupted curses output behind.

I have just verified that this still applies to the lates mtr 0.86 packages in Debian that were uploaded in December 2015.

Please consider fixing this in one of mtr's future releases as it is a severe annoyance in IPv6-only 
networks.

Greetings
Marc

**Comment by aquerubin** [comment] 2016-05-03 01:09
Just want to include for the record that this is really a Debian-unique issue caused by a glibc change, which was later supposedly fixed, but somehow the change is still in older glibc.  If that were true then the latest Debian release would not have this problem, but I confirm it still does.  Confused?  So am I :)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818281

I also confirm the newdns branch of mtr makes the problem moot as it bypasses this bug altogether.  However, I don't think the Debian package maintainer is using newdns.

**Comment by rewolff** [comment] 2016-05-03 05:14
NewDNS was meant to get some "testing". 
Next step should be that the newdns METHOD gets merged into master. Preferably with a run-time switch.

**Comment by aquerubin** [comment] 2016-05-03 05:35
On Mon, 2 May 2016, rewolff wrote:

> NewDNS was meant to get some "testing".

> Next step should be that the newdns METHOD gets merged into master. 
> Preferably with a run-time switch.

Surrounding the newdns stuff in dns.c with an ifdef is easy but the 
autoconfig stuff doesn't look that trivial.  It would be easier to just 
fork the current master as 'olddns' or 'legacy' and merge newdns into 
master.

Either way, it does let the Debian glibc folks off the hook.  I think they 
should fix the problem but mtr is the tail wagging the dog.


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by rewolff** [comment] 2016-08-03 05:57
newdns merged.

**Closed by rewolff** 2016-08-03 05:57 UTC
