### ISSUE TITLE
TCP traceroute is bailing out with address in use error

### ISSUE THREAD

**Issue by PlasmaHH** [traviscross/mtr#275] opened 2018-11-07 11:08 UTC
Running mtr to tcp traceroute with a path full of a lot of packet drops (relative to the interval and timeout combo) seems to leave enough ports open (pure hypothesis) that eventually a bind fails in mtr-packet (strace output):

`bind(86, {sa_family=AF_INET, sin_port=htons(33160), sin_addr=inet_addr("172.19.205.57")}, 16) = -1 EADDRINUSE`

I did not quite understand why it is doing the bind, just the connect should imho suffice but in whatever way it gets to the source port, it seems to be mixing up things here, maybe because the connection did not time out yet and it cycled through the source port again.

**Comment by h0tw1r3** [comment] 2019-05-21 12:13
Confirmed same using command `mtr -z -b -T -P 443 google.com`

**Comment by rewolff** [comment] 2019-05-22 06:20
I had issued that command, concluded it worked fine  here and when I went back to "look for a path with more packetloss is bailed out. So: I can reproduce it here. 

On my system it has nothing to do with packetloss. I get a return of about 100%, zero packetloss. 

OK. I'm a bit further debugging this. mtr starts using ports at 33000 and some "random" process on my system (in my case an ssh session) happened to grab the 425th port after 33000. So after 425 probes it hits a port that's already in use and the bind fails.

**Comment by rewolff** [comment] 2019-05-22 06:35
I added some debug code and the problem still happened, but no debug output. 

Turns out I was using the mtr-packet from my system instead of the freshly compiled one. Using the right one I got the debug message but not the bad behaviour. I consider this "fixed in the latest version from git".

**Closed by rewolff** 2019-05-22 06:35 UTC

**Comment by Ancillius** [comment] 2019-07-10 11:43
Compiled todays git master:

 ~/projects/mtr [master] 
$ sudo mtr ***HOSTNAME*** -T -t 

Still gives mtr: Address in use after 29-30 tries.

**Comment by chrisinmtown** [comment] 2023-02-02 16:44
Please post the mtr version that got the fix. On my mac laptop brew installed mtr version 0.95 which seems to work fine. On a RHEL machine version 0.92 exhibits the address in use problem. Thanks in advance.
